### PR TITLE
mayhem integration

### PR DESCRIPTION
**Pull request by evanrichter**

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
Why were the top level .dockerignore and Dockerfile removed? Upstream will likely not accept this; please restore. Please make the requested changes.

**Review by xansec — CHANGES_REQUESTED** [review]
Please don't remove upstream files.  Please make the requested changes.

**Comment by evanrichter** [comment]
shoot, good catch! it's fixed now

**Review by xansec — APPROVED** [review]
LGTM!

**Pull request merged**
